[phases.setup]
nixPkgs = ["nodejs_22"]
nixpkgsArchive = "ffeebf0acf3ae8b29f8c7049cd911b9636efd7e7"

[phases.install]
cmds = [
  "rm -f package-lock.json",
  "npm install --no-audit --no-fund"
]

[phases.build]
cmds = [
  "rm -rf .nuxt .output",
  "npm run build"
]

[start]
cmd = "node .output/server/index.mjs"
